spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/druginfoservice
    username: postgres
    password: P@sswd1941

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  port: 8081
  tomcat:
    relaxed-query-chars: '|,{,},[,]'
  servlet:
    context-path: /

auth-api:
  username: admin
  password: admin
